### PR TITLE
Fixed Arrow Keys in text editors moves the map (issue #9)

### LINKED ISSUE #9: Using arrow keys in text edit also moves the map
Affects quest editor

### PR DESCRIPTION
**Pull request by eorahil**
Fixed #9 

I added a custom UIInput component. 
When OnSelect is triggered, it disables the cameracontrol pan.
When OnDeselect is triggered, it reenables the cameracontrol pan

### CODE REVIEW

**Comment by eorahil** [comment]
The EndEdit event did the same as OnDeSelect so it was done twice.
I decided to remove this EndEdit procedure (and listener) and leave the OnDeSelect to reactivate PanStrafe

File: unity/Assets/Scripts/Content/DictionaryI18n.cs [hunk 1]
```diff
@@ -262,7 +262,7 @@ public void flushRaw()
             {
                 string key = rawLine.Split(COMMA)[0];
                 // Process non repeated list line
-                if (!dict.ContainsKey(key))
+                if (key != "." && !dict.ContainsKey(key))
```
Comment (NPBruce) [inline unity/Assets/Scripts/Content/DictionaryI18n.cs]: This fix is fine, but I would prefer that separate issues get their own pull request.

Comment (eorahil) [inline unity/Assets/Scripts/Content/DictionaryI18n.cs]: Sorry but I'm creating the editabletextBox with special icons and trying to multiline the field and this issue was "on my way". 
I'm not sure that with this condition all duplicated languages list entry wil dissapear. So I didn't consider this issue fixed.
